services:
  yoinker:
    container_name: music-yoinker
    build: .
    ports:
      - 4534:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MUSIC_DIRECTORY=/app/music
      - DATA_DIRECTORY=/app/data
    volumes:
      - ./music:/app/music:rw
      - ./data:/app/data:rw