services:
  yoinker:
    container_name: music-yoinker
    build: .
    ports:
      - 8080:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MUSIC_DIRECTORY=/app/music
      - DATA_DIRECTORY=/app/data
    volumes:
      - /home/user/Music/:${MUSIC_DIRECTORY}:rw
      - /home/user/data/:${DATA_DIRECTORY}:rw